# Generated by Django 3.0.5 on 2023-05-04 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(default=datetime.date(2023, 5, 4)),
        ),
    ]
